version: '3.7'

services:
  zookeeper:
    container_name: adm_ambev_order_zookeeper
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - 2181:2181
    networks:
      - adm_ambev_order_network

  kafka:
    container_name: adm_ambev_order_kafka
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    ports:
      - 9094:9094
    networks:
      - adm_ambev_order_network

  kafkadrop:
    container_name: kafka_drop
    image: obsidiandynamics/kafdrop:latest
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
    ports:
      - 9000:9000
    networks:
      - adm_ambev_order_network
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - adm_ambev_order_network

  mongoexpress:
    container_name: mongo_express
    image: mongo-express:latest
    restart: always
    networks:
      - adm_ambev_order_network
    depends_on:
      - mongodb
    ports:
      - 9093:8081
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"

networks:
  adm_ambev_order_network: